"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 12:04:29.827781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='NOCASE'), nullable=False),
    sa.Column('tracks_weight', sa.Boolean(), nullable=False),
    sa.Column('tracks_reps', sa.Boolean(), nullable=False),
    sa.Column('tracks_time', sa.Boolean(), nullable=False),
    sa.Column('tracks_distance', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('muscle_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50, collation='NOCASE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='NOCASE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='NOCASE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercise_muscle',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.CheckConstraint("role IN ('primary', 'ancillary')", name='ck_exercise_muscle_role'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group_id')
    )
    op.create_table('log_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'position')
    )
    with op.batch_alter_table('log_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_exercise_date'), ['date'], unique=False)

    op.create_table('muscle_target_default',
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Float(), nullable=False),
    sa.CheckConstraint('sets >= 0', name='ck_muscle_target_default_sets'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], ),
    sa.PrimaryKeyConstraint('muscle_group_id')
    )
    op.create_table('routine_muscle_target',
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Float(), nullable=True),
    sa.CheckConstraint('sets IS NULL OR sets >= 0', name='ck_routine_muscle_target_sets'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('routine_id', 'muscle_group_id')
    )
    op.create_table('routine_workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'position')
    )
    op.create_table('workout_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'position')
    )
    op.create_table('log_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=True),
    sa.Column('target_reps_max', sa.Integer(), nullable=True),
    sa.Column('target_amrap', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(weight IS NULL OR weight >= 0) AND (reps IS NULL OR reps >= 0) AND (duration_seconds IS NULL OR duration_seconds >= 0) AND (distance IS NULL OR distance >= 0)', name='ck_log_set_non_negative'),
    sa.ForeignKeyConstraint(['log_exercise_id'], ['log_exercise.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_exercise_id', 'position')
    )
    op.create_table('workout_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('is_amrap', sa.Boolean(), nullable=False),
    sa.CheckConstraint('NOT is_amrap OR (reps_min IS NULL AND reps_max IS NULL)', name='ck_workout_set_amrap'),
    sa.CheckConstraint('reps_min IS NULL OR reps_max IS NULL OR reps_min <= reps_max', name='ck_workout_set_range'),
    sa.CheckConstraint('reps_min IS NULL OR reps_min >= 1', name='ck_workout_set_min'),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercise.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_exercise_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_set')
    op.drop_table('log_set')
    op.drop_table('workout_exercise')
    op.drop_table('routine_workout')
    op.drop_table('routine_muscle_target')
    op.drop_table('muscle_target_default')
    with op.batch_alter_table('log_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_exercise_date'))

    op.drop_table('log_exercise')
    op.drop_table('exercise_muscle')
    op.drop_table('workout')
    op.drop_table('routine')
    op.drop_table('muscle_group')
    op.drop_table('exercise')
    # ### end Alembic commands ###
