"""set targets for weight time distance

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 12:05:32.715328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_distance', sa.Float(), nullable=True))

    with op.batch_alter_table('workout_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_set', schema=None) as batch_op:
        batch_op.drop_column('distance')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('weight')

    with op.batch_alter_table('log_set', schema=None) as batch_op:
        batch_op.drop_column('target_distance')
        batch_op.drop_column('target_duration_seconds')
        batch_op.drop_column('target_weight')

    # ### end Alembic commands ###
