"""routine cycle days

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 12:25:05.219675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_days', sa.Integer(), server_default='7', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('cycle_days')

    # ### end Alembic commands ###
