"""target presets replace default targets

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-30 12:35:00.873046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='NOCASE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('target_preset_value',
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Float(), nullable=False),
    sa.CheckConstraint('sets >= 0', name='ck_target_preset_value_sets'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['target_preset.id'], ),
    sa.PrimaryKeyConstraint('preset_id', 'muscle_group_id')
    )
    op.drop_table('muscle_target_default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_target_default',
    sa.Column('muscle_group_id', sa.INTEGER(), nullable=False),
    sa.Column('sets', sa.FLOAT(), nullable=False),
    sa.CheckConstraint('sets >= 0', name=op.f('ck_muscle_target_default_sets')),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], ),
    sa.PrimaryKeyConstraint('muscle_group_id')
    )
    op.drop_table('target_preset_value')
    op.drop_table('target_preset')
    # ### end Alembic commands ###
