"""exercise and session notes

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 12:51:06.500663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    with op.batch_alter_table('log_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_exercise', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
